/**
 * @file ResourceManager.h
 * @author Prof. Dr. David Buzatto
 * @brief ResourceManager struct and function declarations.
 * 
 * @copyright Copyright (c) 2026
 */
#pragma once

#include "raylib/raylib.h"

#define MODEL_ATLAS_MAX_SIZE 200

typedef enum {
    MODEL_TYPE_ARROW,
    MODEL_TYPE_ARROWS,
    MODEL_TYPE_BARREL,
    MODEL_TYPE_BLOCK_GRASS,
    MODEL_TYPE_BLOCK_GRASS_CORNER,
    MODEL_TYPE_BLOCK_GRASS_CORNER_LOW,
    MODEL_TYPE_BLOCK_GRASS_CORNER_OVERHANG,
    MODEL_TYPE_BLOCK_GRASS_CORNER_OVERHANG_LOW,
    MODEL_TYPE_BLOCK_GRASS_CURVE,
    MODEL_TYPE_BLOCK_GRASS_CURVE_HALF,
    MODEL_TYPE_BLOCK_GRASS_CURVE_LOW,
    MODEL_TYPE_BLOCK_GRASS_EDGE,
    MODEL_TYPE_BLOCK_GRASS_HEXAGON,
    MODEL_TYPE_BLOCK_GRASS_LARGE,
    MODEL_TYPE_BLOCK_GRASS_LARGE_SLOPE,
    MODEL_TYPE_BLOCK_GRASS_LARGE_SLOPE_NARROW,
    MODEL_TYPE_BLOCK_GRASS_LARGE_SLOPE_STEEP,
    MODEL_TYPE_BLOCK_GRASS_LARGE_SLOPE_STEEP_NARROW,
    MODEL_TYPE_BLOCK_GRASS_LARGE_TALL,
    MODEL_TYPE_BLOCK_GRASS_LONG,
    MODEL_TYPE_BLOCK_GRASS_LOW,
    MODEL_TYPE_BLOCK_GRASS_LOW_HEXAGON,
    MODEL_TYPE_BLOCK_GRASS_LOW_LARGE,
    MODEL_TYPE_BLOCK_GRASS_LOW_LONG,
    MODEL_TYPE_BLOCK_GRASS_LOW_NARROW,
    MODEL_TYPE_BLOCK_GRASS_NARROW,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_CORNER,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_EDGE,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_HEXAGON,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LARGE,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LARGE_SLOPE,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LARGE_SLOPE_NARROW,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LARGE_SLOPE_STEEP,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LARGE_SLOPE_STEEP_NARROW,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LARGE_TALL,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LONG,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LOW,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LOW_HEXAGON,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LOW_LARGE,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LOW_LONG,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_LOW_NARROW,
    MODEL_TYPE_BLOCK_GRASS_OVERHANG_NARROW,
    MODEL_TYPE_BLOCK_MOVING,
    MODEL_TYPE_BLOCK_MOVING_BLUE,
    MODEL_TYPE_BLOCK_MOVING_LARGE,
    MODEL_TYPE_BLOCK_SNOW,
    MODEL_TYPE_BLOCK_SNOW_CORNER,
    MODEL_TYPE_BLOCK_SNOW_CORNER_LOW,
    MODEL_TYPE_BLOCK_SNOW_CORNER_OVERHANG,
    MODEL_TYPE_BLOCK_SNOW_CORNER_OVERHANG_LOW,
    MODEL_TYPE_BLOCK_SNOW_CURVE,
    MODEL_TYPE_BLOCK_SNOW_CURVE_HALF,
    MODEL_TYPE_BLOCK_SNOW_CURVE_LOW,
    MODEL_TYPE_BLOCK_SNOW_EDGE,
    MODEL_TYPE_BLOCK_SNOW_HEXAGON,
    MODEL_TYPE_BLOCK_SNOW_LARGE,
    MODEL_TYPE_BLOCK_SNOW_LARGE_SLOPE,
    MODEL_TYPE_BLOCK_SNOW_LARGE_SLOPE_NARROW,
    MODEL_TYPE_BLOCK_SNOW_LARGE_SLOPE_STEEP,
    MODEL_TYPE_BLOCK_SNOW_LARGE_SLOPE_STEEP_NARROW,
    MODEL_TYPE_BLOCK_SNOW_LARGE_TALL,
    MODEL_TYPE_BLOCK_SNOW_LONG,
    MODEL_TYPE_BLOCK_SNOW_LOW,
    MODEL_TYPE_BLOCK_SNOW_LOW_HEXAGON,
    MODEL_TYPE_BLOCK_SNOW_LOW_LARGE,
    MODEL_TYPE_BLOCK_SNOW_LOW_LONG,
    MODEL_TYPE_BLOCK_SNOW_LOW_NARROW,
    MODEL_TYPE_BLOCK_SNOW_NARROW,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_CORNER,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_EDGE,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_HEXAGON,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LARGE,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LARGE_SLOPE,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LARGE_SLOPE_NARROW,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LARGE_SLOPE_STEEP,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LARGE_SLOPE_STEEP_NARROW,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LARGE_TALL,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LONG,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LOW,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LOW_HEXAGON,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LOW_LARGE,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LOW_LONG,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_LOW_NARROW,
    MODEL_TYPE_BLOCK_SNOW_OVERHANG_NARROW,
    MODEL_TYPE_BOMB,
    MODEL_TYPE_BRICK,
    MODEL_TYPE_BUTTON_ROUND,
    MODEL_TYPE_BUTTON_SQUARE,
    MODEL_TYPE_CHARACTER_OOBI,
    MODEL_TYPE_CHARACTER_OODI,
    MODEL_TYPE_CHARACTER_OOLI,
    MODEL_TYPE_CHARACTER_OOPI,
    MODEL_TYPE_CHARACTER_OOZI,
    MODEL_TYPE_CHEST,
    MODEL_TYPE_COIN_BRONZE,
    MODEL_TYPE_COIN_GOLD,
    MODEL_TYPE_COIN_SILVER,
    MODEL_TYPE_CONVEYOR_BELT,
    MODEL_TYPE_CRATE,
    MODEL_TYPE_CRATE_ITEM,
    MODEL_TYPE_CRATE_ITEM_STRONG,
    MODEL_TYPE_CRATE_STRONG,
    MODEL_TYPE_DOOR_LARGE_OPEN,
    MODEL_TYPE_DOOR_OPEN,
    MODEL_TYPE_DOOR_ROTATE,
    MODEL_TYPE_DOOR_ROTATE_LARGE,
    MODEL_TYPE_FENCE_BROKEN,
    MODEL_TYPE_FENCE_CORNER,
    MODEL_TYPE_FENCE_CORNER_CURVED,
    MODEL_TYPE_FENCE_LOW_BROKEN,
    MODEL_TYPE_FENCE_LOW_CORNER,
    MODEL_TYPE_FENCE_LOW_CORNER_CURVED,
    MODEL_TYPE_FENCE_LOW_STRAIGHT,
    MODEL_TYPE_FENCE_ROPE,
    MODEL_TYPE_FENCE_STRAIGHT,
    MODEL_TYPE_FLAG,
    MODEL_TYPE_FLOWERS,
    MODEL_TYPE_FLOWERS_TALL,
    MODEL_TYPE_GRASS,
    MODEL_TYPE_HEART,
    MODEL_TYPE_HEDGE,
    MODEL_TYPE_HEDGE_CORNER,
    MODEL_TYPE_JEWEL,
    MODEL_TYPE_KEY,
    MODEL_TYPE_LADDER,
    MODEL_TYPE_LADDER_BROKEN,
    MODEL_TYPE_LADDER_LONG,
    MODEL_TYPE_LEVER,
    MODEL_TYPE_LOCK,
    MODEL_TYPE_MUSHROOMS,
    MODEL_TYPE_PIPE,
    MODEL_TYPE_PLANT,
    MODEL_TYPE_PLATFORM,
    MODEL_TYPE_PLATFORM_FORTIFIED,
    MODEL_TYPE_PLATFORM_OVERHANG,
    MODEL_TYPE_PLATFORM_RAMP,
    MODEL_TYPE_POLES,
    MODEL_TYPE_ROCKS,
    MODEL_TYPE_SAW,
    MODEL_TYPE_SIGN,
    MODEL_TYPE_SPIKE_BLOCK,
    MODEL_TYPE_SPIKE_BLOCK_WIDE,
    MODEL_TYPE_SPRING,
    MODEL_TYPE_STAR,
    MODEL_TYPE_STONES,
    MODEL_TYPE_TRAP_SPIKES,
    MODEL_TYPE_TRAP_SPIKES_LARGE,
    MODEL_TYPE_TREE,
    MODEL_TYPE_TREE_PINE,
    MODEL_TYPE_TREE_PINE_SMALL,
    MODEL_TYPE_TREE_PINE_SNOW,
    MODEL_TYPE_TREE_PINE_SNOW_SMALL,
    MODEL_TYPE_TREE_SNOW,
} MapPieceModelType;

typedef struct {
    MapPieceModelType type;
    char path[200];
} MapPieceModelTypeAndPathMapping;

typedef struct ResourceManager {

    int mapPieceModelAtlasCount;
    Model *mapPieceModelAtlas;

    Font baseFont;

    Texture2D mapPieceModelAtlasPreviewTexture;

    /*Texture2D textureExample;
    Sound soundExample;
    Music musicExample;*/

} ResourceManager;

// Read-only outside this module. Use rm->field to access resources.
extern const ResourceManager * const rm;

/**
 * @brief Load global game resources, linking them in the global instance of
 * ResourceManager called rm.
 */
void loadResourcesResourceManager( void );

/**
 * @brief Unload global game resources.
 */
void unloadResourcesResourceManager( void );